/**
 * Generated by Verge3D Puzzles v.3.4.0
 * Fri Nov 13 2020 20:14:23 GMT+0300 (Moscow Standard Time)
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */

'use strict';

(function() {

// global variables/constants used by puzzles' functions

var LIST_NONE = '<none>';

var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.objClickInfo = [];
_pGlob.pickedObject = '';
_pGlob.objHoverInfo = [];
_pGlob.hoveredObject = '';
_pGlob.objMovementInfos = {};
_pGlob.objDragOverCallbacks = [];
_pGlob.objDragOverInfoByBlock = {}
_pGlob.dragMoveOrigins = {};
_pGlob.dragScaleOrigins = {};
_pGlob.mediaElements = {};
_pGlob.loadedFiles = {};
_pGlob.loadedFile = '';
_pGlob.promiseValue = '';
_pGlob.animMixerCallbacks = [];
_pGlob.arHitPoint = new v3d.Vector3(0, 0, 0);
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.animateParamUpdate = null;
_pGlob.openedFile = '';
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.gamepadIndex = 0;

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster();
_pGlob.intervals = {};

var _pPhysics = {};

_pPhysics.tickCallbacks = [];
_pPhysics.syncList = [];
_pPhysics.consList = [];

// internal info
_pPhysics.collisionData = [];

// goes to collision callback
_pPhysics.collisionInfo = {
    objectA: '',
    objectB: '',
    distance: 0,
    positionOnA: [0, 0, 0],
    positionOnB: [0, 0, 0],
    normalOnB: [0, 0, 0]
};

var _noWebAudioReported = false;

var PL = v3d.PL = v3d.PL || {};

// a more readable alias for PL (stands for "Puzzle Logic")
v3d.puzzles = PL;

PL.procedures = PL.procedures || {};

_pGlob.wooProductInfo = {};

PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;

    var _initGlob = {};
    _initGlob.percentage = 0;
    _initGlob.output = {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        }
    }

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    var PROC = {
    
};


// loadFont puzzle
function loadFont(url, family) {

    if (!url || !family)
        return;

    // register in CSS
    var elemStyle = document.createElement('style');
    elemStyle.innerHTML = '@font-face { font-family: ' + family
        + '; src: url(' + url + '); }';
    document.body.appendChild(elemStyle);

    // preload font
    var elemDiv = document.createElement('div');
    elemDiv.innerHTML = 'invisible text';
    elemDiv.style.visibility = 'hidden';
    elemDiv.style.fontFamily = family;
    document.body.appendChild(elemDiv);
}



// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}



// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if (attr === 'style') {
            // NOTE: setting an attribute 'style' instead of a property 'style'
            // fixes IE11 worng behavior
            elem.setAttribute(attr, value);
        } else {
            elem[attr] = value;
        }
    }
}




// initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = true;
_initGlob.output.initOptions.useFullscreen = false;

loadFont('./fonts/DaysOne-Regular.ttf', 'days-one');
loadFont('./fonts/Bellefair-Regular.ttf', 'bellefair');
loadFont('./fonts/Caveat-Regular.ttf', 'caveat');
loadFont('./fonts/GreatVibes-Regular.ttf', 'great_vibes');
loadFont('./fonts/Lobster-Regular.ttf', 'lobster');


// initPreloader puzzle
_initGlob.output.initOptions.useCustomPreloader = true;
_initGlob.output.initOptions.preloaderStartCb = function() {
    _initGlob.percentage = 0;
    (function() {
  setHTMLElemStyle('display', 'block', 'preloader_conteiner', true);
})();
};
_initGlob.output.initOptions.preloaderProgressCb = function(percentage) {
    _initGlob.percentage = percentage;
    (function() {
  setHTMLElemStyle('height', String(Math.round(Math.round(_initGlob.percentage) / 4)) + '%', 'preloader_color', true);
  setHTMLElemAttribute('innerHTML', String(Math.round(Math.round(_initGlob.percentage) / 4)) + '%', 'preloader_percentage', true);
})();
};
_initGlob.output.initOptions.preloaderEndCb = function() {
    _initGlob.percentage = 100;
    (function() {})();
};

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {
initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["ring_update"] = ring_update;
this.procedures["update_engraving"] = update_engraving;
this.procedures["metall_material_update"] = metall_material_update;
this.procedures["gem_color_update"] = gem_color_update;
this.procedures["buttons_select_remove"] = buttons_select_remove;
this.procedures["buttons_select_apply"] = buttons_select_apply;
this.procedures["html_buttons_acess_update"] = html_buttons_acess_update;
this.procedures["load_gem_set"] = load_gem_set;

var PROC = {
    "ring_update": ring_update,
    "update_engraving": update_engraving,
    "metall_material_update": metall_material_update,
    "gem_color_update": gem_color_update,
    "buttons_select_remove": buttons_select_remove,
    "buttons_select_apply": buttons_select_apply,
    "html_buttons_acess_update": html_buttons_acess_update,
    "load_gem_set": load_gem_set,
};

var current_ring, metall_colors, gem_number, ring_type, engraving_ao, gem_colors, gem_type, engraving_normal, line_type, curve_type, material, gem_color, pearl_color, i, gem_loaded, i_count;


// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}



// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}



// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if (attr === 'style') {
            // NOTE: setting an attribute 'style' instead of a property 'style'
            // fixes IE11 worng behavior
            elem.setAttribute(attr, value);
        } else {
            elem[attr] = value;
        }
    }
}



// appendScene puzzle
function appendScene(url, sceneName, loadCameras, loadLights, loadCb, progCb) {
    _pGlob.percentage = 0;

    appInstance.appendScene(url, function(loadedScene) {
        loadedScene.name = sceneName;
        _pGlob.percentage = 100;
        loadCb();
    }, function(percentage) {
        _pGlob.percentage = percentage;
        progCb();
    }, null, loadCameras, loadLights);
}



// featureAvailable puzzle
function featureAvailable(feature) {

    var userAgent = window.navigator.userAgent;
    var platform = window.navigator.platform;

    switch (feature) {
    case 'LINUX':
        return /Linux/.test(platform);
    case 'WINDOWS':
        return ['Win32', 'Win64', 'Windows', 'WinCE'].indexOf(platform) !== -1;
    case 'MACOS':
        return (['Macintosh', 'MacIntel', 'MacPPC', 'Mac68K'].indexOf(platform) !== -1 && !v3d.Detector.checkIOS());
    case 'IOS':
        return v3d.Detector.checkIOS();
    case 'ANDROID':
        return /Android/i.test(userAgent);
    case 'MOBILE':
        return (/Android|webOS|BlackBerry/i.test(userAgent) || v3d.Detector.checkIOS());

    case 'CHROME':
        // Chromium based
        return (!!window.chrome && !/Edge/.test(navigator.userAgent));
    case 'FIREFOX':
        return /Firefox/.test(navigator.userAgent);
    case 'IE':
        return /Trident/.test(navigator.userAgent);
    case 'EDGE':
        return /Edge/.test(navigator.userAgent);
    case 'SAFARI':
        return (/Safari/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent));

    case 'TOUCH':
        return !!(('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch);
    case 'RETINA':
        return window.devicePixelRatio >= 2;
    case 'HDR':
        return appInstance.useHDR;
    case 'WEBAUDIO':
        return v3d.Detector.checkWebAudio();
    case 'WEBGL2':
        var canvas = document.createElement('canvas');
        var gl = canvas.getContext('webgl2')
        return !!gl;
    case 'WOOCOMMERCE':
        var woo_fun = window.parent.v3d_woo_get_product_info || window.parent.parent.v3d_woo_get_product_info;
        return !!woo_fun;
    default:
        return false;
    }

}




// utility function envoked by almost all V3D-specific puzzles
// filter off some non-mesh types
function notIgnoredObj(obj) {
    return (obj.type !== "AmbientLight" && obj.name !== ""
            && !(obj.isMesh && obj.isMaterialGeneratedMesh));
}


// utility function envoked by almost all V3D-specific puzzles
// find first occurence of the object by its name
function getObjectByName(objName) {
    var objFound;
    var runTime = _pGlob !== undefined;
    objFound = runTime ? _pGlob.objCache[objName] : null;

    if (objFound && objFound.name === objName)
        return objFound;

    appInstance.scene.traverse(function(obj) {
        if (!objFound && notIgnoredObj(obj) && (obj.name == objName)) {
            objFound = obj;
            if (runTime) {
                _pGlob.objCache[objName] = objFound;
            }
        }
    });
    return objFound;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects on the scene
function getAllObjectNames() {
    var objNameList = [];
    appInstance.scene.traverse(function(obj) {
        if (notIgnoredObj(obj))
            objNameList.push(obj.name)
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects which belong to the group
function getObjectNamesByGroupName(targetGroupName) {
    var objNameList = [];
    appInstance.scene.traverse(function(obj){
        if (notIgnoredObj(obj)) {
            var groupNames = obj.groupNames;
            if (!groupNames)
                return;
            for (var i = 0; i < groupNames.length; i++) {
                var groupName = groupNames[i];
                if (groupName == targetGroupName) {
                    objNameList.push(obj.name);
                }
            }
        }
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// process object input, which can be either single obj or array of objects, or a group
function retrieveObjectNames(objNames) {
    var acc = [];
    retrieveObjectNamesAcc(objNames, acc);
    return acc;
}

function retrieveObjectNamesAcc(currObjNames, acc) {
    if (typeof currObjNames == "string") {
        acc.push(currObjNames);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "GROUP") {
        var newObj = getObjectNamesByGroupName(currObjNames[1]);
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "ALL_OBJECTS") {
        var newObj = getAllObjectNames();
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames)) {
        for (var i = 0; i < currObjNames.length; i++)
            retrieveObjectNamesAcc(currObjNames[i], acc);
    }
}





/**
 * Retrieve coordinate system from the loaded scene
 */
function getCoordSystem() {
    var scene = appInstance.scene;

    if (scene && "v3d" in scene.userData && "coordSystem" in scene.userData.v3d) {
        return scene.userData.v3d.coordSystem;
    } else {
        // COMPAT: <2.17, consider replacing to 'Y_UP_RIGHT' for scenes with unknown origin
        return 'Z_UP_RIGHT';
    }
}


/**
 * Transform coordinates from one space to another
 * Can be used with Vector3 or Euler.
 */
function coordsTransform(coords, from, to, noSignChange) {

    if (from == to)
        return coords;

    var y = coords.y, z = coords.z;

    if (from == 'Z_UP_RIGHT' && to == 'Y_UP_RIGHT') {
        coords.y = z;
        coords.z = noSignChange ? y : -y;
    } else if (from == 'Y_UP_RIGHT' && to == 'Z_UP_RIGHT') {
        coords.y = noSignChange ? z : -z;
        coords.z = y;
    } else {
        console.error('coordsTransform: Unsupported coordinate space');
    }

    return coords;
}


/**
 * Verge3D euler rotation to Blender/Max shortest.
 * 1) Convert from intrinsic rotation (v3d) to extrinsic XYZ (Blender/Max default
 *    order) via reversion: XYZ -> ZYX
 * 2) swizzle ZYX->YZX
 * 3) choose the shortest rotation to resemble Blender's behavior
 */
var eulerV3DToBlenderShortest = function() {

    var eulerTmp = new v3d.Euler();
    var eulerTmp2 = new v3d.Euler();
    var vec3Tmp = new v3d.Vector3();

    return function(euler, dest) {

        var eulerBlender = eulerTmp.copy(euler).reorder('YZX');
        var eulerBlenderAlt = eulerTmp2.copy(eulerBlender).makeAlternative();

        var len = eulerBlender.toVector3(vec3Tmp).lengthSq();
        var lenAlt = eulerBlenderAlt.toVector3(vec3Tmp).lengthSq();

        dest.copy(len < lenAlt ? eulerBlender : eulerBlenderAlt);
        return coordsTransform(dest, 'Y_UP_RIGHT', 'Z_UP_RIGHT');
    }

}();




// tweenCamera puzzle
function tweenCamera(posOrObj, targetOrObj, duration, doSlot, movementType) {

    if (Array.isArray(posOrObj)) {
        var worldPos = _pGlob.vec3Tmp.fromArray(posOrObj);
        worldPos = coordsTransform(worldPos, getCoordSystem(), 'Y_UP_RIGHT');
    } else if (posOrObj) {
        var posObj = getObjectByName(posOrObj);
        if (!posObj) return;
        var worldPos = posObj.getWorldPosition(_pGlob.vec3Tmp);
    } else {
        // empty input means: don't change the position
        var worldPos = appInstance.camera.getWorldPosition(_pGlob.vec3Tmp);
    }

    if (Array.isArray(targetOrObj)) {
        var worldTarget = _pGlob.vec3Tmp2.fromArray(targetOrObj);
        worldTarget = coordsTransform(worldTarget, getCoordSystem(), 'Y_UP_RIGHT');
    } else {
        var targObj = getObjectByName(targetOrObj);
        if (!targObj) return;
        var worldTarget = targObj.getWorldPosition(_pGlob.vec3Tmp2);
    }

    duration = Math.max(0, duration);

    if (appInstance.controls && appInstance.controls.tween) {
        // orbit and flying cameras
        if (!appInstance.controls.inTween) {
            appInstance.controls.tween(worldPos, worldTarget, duration, doSlot,
                    movementType);
        }
    } else {
        // TODO: static camera, just position it for now
        if (appInstance.camera.parent) {
            appInstance.camera.parent.worldToLocal(worldPos);
        }
        appInstance.camera.position.copy(worldPos);
        appInstance.camera.lookAt(worldTarget);
        doSlot();
    }
}



// bloom puzzle
function bloom(threshold, strength, radius) {
    appInstance.enablePostprocessing([{
        type: 'bloom',
        threshold: threshold,
        strength: strength,
        radius: radius
    }]);
}



function setScreenScale(factor) {
    appInstance.renderer.setPixelRatio(factor);
    // to update possible post-processing passes
    appInstance.onResize();
}



// isObjectVisible puzzle
function isObjectVisible(objNames) {
    objNames = retrieveObjectNames(objNames);
    if (!objNames)
        return false;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = getObjectByName(objName);
        if (!obj)
            continue;
        if (obj.visible)
            return true;
    }
    return false;
}



// show and hide puzzles
function changeVis(objNames, bool) {
    objNames = retrieveObjectNames(objNames);
    if (!objNames)
        return;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
    }
}



// removePostprocessing puzzle
function removePostprocessing() {
    // keep outline
    appInstance.disablePostprocessing(true);
}



// ssr puzzle
function ssr(type, matName, steps, stride, binarySearchSteps, thickness,
        maxDistance, resolution, jitter, renderAfterNames) {

    var useRefract = (type == 'REFRACT') ? true : false;

    var matNames = Array.isArray(matName) ? matName : [matName];
    var mats = [];

    matNames.forEach(function(name) {
        mats = mats.concat(v3d.SceneUtils.getMaterialsByName(appInstance, name));
    });

    var objects = [];

    for (var i = 0; i < mats.length; i++) {
        var mat = mats[i];

        appInstance.scene.traverse(function(obj) {
            if (obj.material && obj.material == mat)
                objects.push(obj);
        });
    }

    // no need
    if (!objects.length)
        return;

    var renderAfter = [];

    renderAfterNames = retrieveObjectNames(renderAfterNames);
    if (!renderAfterNames)
        return;

    for (var i = 0; i < renderAfterNames.length; i++) {
        var obj = getObjectByName(renderAfterNames[i]);
        if (obj)
            renderAfter.push(obj);
    }

    appInstance.enablePostprocessing([{
        type: 'ssr',
        useRefract: useRefract,
        objects: objects,
        steps: steps,
        stride: stride,
        binarySearchSteps: binarySearchSteps,
        thickness: thickness,
        maxDistance: maxDistance,
        renderTargetScale: resolution,
        jitter: jitter,
        renderAfter: renderAfter
    }]);
}


// Describe this function...
function ring_update() {
  if (isObjectVisible(['ring_type_',ring_type,'_gem_',gem_type,'_curve_',curve_type,'_line_',line_type].join('')) == false) {
    changeVis('ring_' + String(current_ring), false);
    changeVis(['gem_',current_ring,'_outside'].join(''), false);
    changeVis(['gem_',current_ring,'_outside_1'].join(''), false);
    changeVis(['gem_',current_ring,'_outside_2'].join(''), false);
    changeVis(['gem_',current_ring,'_inside'].join(''), false);
    changeVis(['gem_',current_ring,'_inside_1'].join(''), false);
    changeVis(['gem_',current_ring,'_inside_2'].join(''), false);
    removePostprocessing();
    current_ring = ['type_',ring_type,'_gem_',gem_type,'_curve_',curve_type,'_line_',line_type].join('');
    ssr('REFRACT', 'gem_outer', 300, 1,
                4, 0.03, 0.1, 1,
                1, ['ring_' + String(current_ring), 'Plane']);
    changeVis('ring_' + String(current_ring), true);
    changeVis(['gem_',current_ring,'_outside'].join(''), true);
    changeVis(['gem_',current_ring,'_outside_1'].join(''), true);
    changeVis(['gem_',current_ring,'_outside_2'].join(''), true);
    changeVis(['gem_',current_ring,'_inside'].join(''), true);
    changeVis(['gem_',current_ring,'_inside_1'].join(''), true);
    changeVis(['gem_',current_ring,'_inside_2'].join(''), true);
    if (featureAvailable('MOBILE') == false) {
      bloom(1, 0.3, 0.5);
    }
  }
  buttons_select_apply();
}


// getHTMLElemAttribute puzzle
function getHTMLElemAttribute(attr, id, isParent) {
    var elem = getElement(id, isParent);
    return elem ? elem[attr]: '';
}



// textureFromText puzzle
function textureFromText(text, width, height, family, size, align, offset) {

    var canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    var ctx = canvas.getContext('2d');
    // clear color first to prevent severe pixelating
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.font = size + 'px ' + family;
    ctx.fillStyle = 'black';

    var x;
    switch (align) {
    case 'CENTER':
        ctx.textAlign = 'center';
        x = width/2;
        break;
    case 'LEFT':
        ctx.textAlign = 'left';
        x = offset;
        break;
    case 'RIGHT':
        ctx.textAlign = 'right';
        x = width - offset;
        break;
    case 'FIT':
        function fit(min, max) {
            if (max - min < 1)
                return min;
            var test = min + (max - min)/2;
            ctx.font = test + 'px ' + family;
            var measured = ctx.measureText(text).width;
            return (measured > width - 2 * offset) ? fit(min, test) : fit(test, max);
        }
        size = fit(0, height);
        x = offset;
        // no fit performed
        if ((height - size) < 1) {
            ctx.textAlign = 'center';
            x = width/2;
        }
        break;
    }
    var y = height/2 + size/4;
    ctx.fillText(text, x, y);
    return canvas.toDataURL();
}



/*
    Converts a pre-loaded image to normal map, returned as new image in Data URL format.
    Parameters:
    {
        width: 256, // pixels
        height: 256, // pixels
        strength: 2.5, // 0.01 to 5
        level: 7.0, // 4 to 10
        blur: 0.0, // -32 to 32
        filter: 'Sobel', // or 'Scharr'
        invertR: false,
        invertG: false,
        invertHeight: false
    }
    Based on NormalMap Online by Christian Petry
    Source: https://github.com/cpetry/NormalMap-Online
    Live: https://cpetry.github.io/NormalMap-Online/
*/

var NORMALGEN = NORMALGEN || {};

NORMALGEN.normalCanvas = null;
NORMALGEN.renderer = null;

NORMALGEN.convert = function(heightImage, params) {

    // init renderer
	var normalCanvas = NORMALGEN.normalCanvas = NORMALGEN.normalCanvas ||
		document.createElement('canvas');
	var renderer = NORMALGEN.renderer = NORMALGEN.renderer ||
		new v3d.WebGLRenderer({ alpha: false, antialias: true, canvas: normalCanvas });
	renderer.setSize(params.width, params.height);

	// init normal map shader
	var normalShader = NORMALGEN.NormalMapShader;
	var normalUniforms = v3d.UniformsUtils.clone(normalShader.uniforms);

    // set width and height
    normalUniforms['dimensions'].value =
        [params.width, params.height, 0];

    // set strength and level
    normalUniforms['dz'].value =
        1.0 / params.strength * (1.0 + Math.pow(2.0, params.level));

    // set filter
    normalUniforms['type'].value = (params.filter == 'Sobel') ? 0 : 1;

    // set inversion flags
    normalUniforms['invertR'].value = params.invertR ? -1 : 1;
    normalUniforms['invertG'].value = params.invertG ? -1 : 1;
    normalUniforms['invertH'].value = params.invertHeight ? -1 : 1;

    // setup texture
	var heightTex		  = new v3d.Texture(heightImage);
	heightTex.minFilter   = heightTex.magFilter = v3d.NearestFilter;
	heightTex.needsUpdate = true;
	normalUniforms['tHeightMap'].value = heightTex;

    // setup material
	var normalMat = new v3d.ShaderMaterial({
		fragmentShader: normalShader.fragmentShader,
		vertexShader: normalShader.vertexShader,
		uniforms: normalUniforms
	});

    // setup mesh
	var geometry = new v3d.PlaneBufferGeometry(1, 1, 1, 1);
	var mesh = new v3d.Mesh(geometry, normalMat);
	mesh.name = 'NORMALGEN_MESH';

    // setup scene
	var scene = new v3d.Scene();
	scene.add(mesh);
	var camera = new v3d.OrthographicCamera(1/-2, 1/2, 1/2, 1/-2, 0, 1);
	var normalPass = new v3d.RenderPass(scene, camera);

	// blur passes
	var gaussianPassY = new v3d.ShaderPass(NORMALGEN.VerticalBlurShader);
	var gaussianPassX = new v3d.ShaderPass(NORMALGEN.HorizontalBlurShader);

    // set blur params
	gaussianPassY.uniforms['v'].value = params.blur / params.width / 5;
	gaussianPassX.uniforms['h'].value = params.blur / params.height / 5;

    // setup render target
	var rtParams = { minFilter: v3d.NearestFilter, magFilter: v3d.NearestFilter,
	    format: v3d.RGBAFormat, stencilBufer: false };
	var renderTarget = new v3d.WebGLRenderTarget(params.width, params.height, rtParams);

    // setup composer
	var composer = new v3d.EffectComposer(renderer, renderTarget);
	composer.setSize(params.width, params.height);
	composer.addPass(normalPass);
	composer.addPass(gaussianPassY);
	composer.addPass(gaussianPassX);

    // draw
    composer.render(1/60);

	// retrieve image
	var resultImage = normalCanvas.toDataURL();

	// clean up
	normalMat.dispose();
	scene.dispose();
	composer.dispose();
	renderer.dispose();

	return resultImage;
}


NORMALGEN.NormalMapShader = {
	uniforms: {
		'type': 		{type: '1i', value: 0},
    	'invertR': 		{type: '1f', value: 1},
    	'invertG': 		{type: '1f', value: 1},
    	'invertH': 		{type: '1f', value: 1},
    	'dz':           {type: '1f', value: 0},
    	'dimensions': 	{type: 'fv', value: [0, 0, 0]},
    	'tHeightMap': 	{type: 't', value: null }
	},

	vertexShader: [
		'precision mediump float;',
        'varying vec2 vUv;',
		'varying vec2 step;',
        'uniform vec3 dimensions;',
        'void main() {',
			'gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',
			'step = vec2(-1.0 / dimensions.x, -1.0 / dimensions.y);', // - to switch from glsl orientation to my orientation :D
			'vUv = uv;',
		'}'
	].join('\n'),

	fragmentShader: [
		'precision mediump float;',
        'uniform vec3 dimensions;',
        'varying vec2 vUv;',
        'varying vec2 step;',
        'uniform float dz;',
        'uniform float invertR;',
        'uniform float invertG;',
        'uniform float invertH;',
        'uniform int type;',
		'uniform sampler2D tHeightMap;',

		'void main(void) {',
		'	vec2 tlv = vec2(vUv.x - step.x, vUv.y + step.y );',
		'	vec2 lv  = vec2(vUv.x - step.x, vUv.y 		   );',
		'	vec2 blv = vec2(vUv.x - step.x, vUv.y - step.y);',
		'	vec2 tv  = vec2(vUv.x 		  , vUv.y + step.y );',
		'	vec2 bv  = vec2(vUv.x 		  , vUv.y - step.y);',
		'	vec2 trv = vec2(vUv.x + step.x, vUv.y + step.y );',
		'	vec2 rv  = vec2(vUv.x + step.x, vUv.y 		   );',
		'	vec2 brv = vec2(vUv.x + step.x, vUv.y - step.y);',
		'	tlv = vec2(tlv.x >= 0.0 ? tlv.x : (1.0 + tlv.x), 	tlv.y >= 0.0	? tlv.y : (1.0  + tlv.y));',
		'	tlv = vec2(tlv.x < 1.0  ? tlv.x : (tlv.x - 1.0 ), 	tlv.y < 1.0   	? tlv.y : (tlv.y - 1.0 ));',
		'	lv  = vec2( lv.x >= 0.0 ?  lv.x : (1.0 + lv.x),  	lv.y  >= 0.0 	?  lv.y : (1.0  +  lv.y));',
		'	lv  = vec2( lv.x < 1.0  ?  lv.x : ( lv.x - 1.0 ),   lv.y  < 1.0  	?  lv.y : ( lv.y - 1.0 ));',
		'	blv = vec2(blv.x >= 0.0 ? blv.x : (1.0 + blv.x), 	blv.y >= 0.0 	? blv.y : (1.0  + blv.y));',
		'	blv = vec2(blv.x < 1.0  ? blv.x : (blv.x - 1.0 ), 	blv.y < 1.0 	? blv.y : (blv.y - 1.0 ));',
		'	tv  = vec2( tv.x >= 0.0 ?  tv.x : (1.0 + tv.x),  	tv.y  >= 0.0 	?  tv.y : (1.0  +  tv.y));',
		'	tv  = vec2( tv.x < 1.0  ?  tv.x : ( tv.x - 1.0 ),   tv.y  < 1.0 	?  tv.y : ( tv.y - 1.0 ));',
		'	bv  = vec2( bv.x >= 0.0 ?  bv.x : (1.0 + bv.x),  	bv.y  >= 0.0 	?  bv.y : (1.0  +  bv.y));',
		'	bv  = vec2( bv.x < 1.0  ?  bv.x : ( bv.x - 1.0 ),   bv.y  < 1.0 	?  bv.y : ( bv.y - 1.0 ));',
		'	trv = vec2(trv.x >= 0.0 ? trv.x : (1.0 + trv.x), 	trv.y >= 0.0 	? trv.y : (1.0  + trv.y));',
		'	trv = vec2(trv.x < 1.0  ? trv.x : (trv.x - 1.0 ), 	trv.y < 1.0   	? trv.y : (trv.y - 1.0 ));',
		'	rv  = vec2( rv.x >= 0.0 ?  rv.x : (1.0 + rv.x),  	rv.y  >= 0.0 	?  rv.y : (1.0  +  rv.y));',
		'	rv  = vec2( rv.x < 1.0  ?  rv.x : ( rv.x - 1.0 ),   rv.y  < 1.0   	?  rv.y : ( rv.y - 1.0 ));',
		'	brv = vec2(brv.x >= 0.0 ? brv.x : (1.0 + brv.x), 	brv.y >= 0.0 	? brv.y : (1.0  + brv.y));',
		'	brv = vec2(brv.x < 1.0  ? brv.x : (brv.x - 1.0 ), 	brv.y < 1.0   	? brv.y : (brv.y - 1.0 ));',
		'	float tl = abs(texture2D(tHeightMap, tlv).r);',
		'	float l  = abs(texture2D(tHeightMap, lv ).r);',
		'	float bl = abs(texture2D(tHeightMap, blv).r);',
		'	float t  = abs(texture2D(tHeightMap, tv ).r);',
		'	float b  = abs(texture2D(tHeightMap, bv ).r);',
		'	float tr = abs(texture2D(tHeightMap, trv).r);',
		'	float r  = abs(texture2D(tHeightMap, rv ).r);',
		'	float br = abs(texture2D(tHeightMap, brv).r);',
		'   float dx = 0.0, dy = 0.0;',
		'   if(type == 0){',	// Sobel
		'		dx = tl + l*2.0 + bl - tr - r*2.0 - br;',
		'		dy = tl + t*2.0 + tr - bl - b*2.0 - br;',
		'   }',
		'   else{',				// Scharr
		'		dx = tl*3.0 + l*10.0 + bl*3.0 - tr*3.0 - r*10.0 - br*3.0;',
		'		dy = tl*3.0 + t*10.0 + tr*3.0 - bl*3.0 - b*10.0 - br*3.0;',
		'   }',
		'	vec4 normal = vec4(normalize(vec3(dx * invertR * invertH * 255.0, dy * invertG * invertH * 255.0, dz)), texture2D(tHeightMap, vUv).a);',
		'	gl_FragColor = vec4(normal.xy * 0.5 + 0.5, normal.zw);',
		'}'
	].join('\n')
};


NORMALGEN.HorizontalBlurShader = {

	uniforms: {

		'tDiffuse': { type: 't', value: null },
		'h':        { type: 'f', value: 3.0 / 512.0 }

	},

	vertexShader: [

		'varying vec2 vUv;',

		'void main() {',

			'vUv = uv;',
			'gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',

		'}'

	].join('\n'),

	fragmentShader: [

		'uniform sampler2D tDiffuse;',
		'uniform float h;',

		'varying vec2 vUv;',

		'void main() {',

			'vec4 sum = vec4( 0.0 );',
			'float lef4 = vUv.x - 4.0 * h;',
			'float lef3 = vUv.x - 3.0 * h;',
			'float lef2 = vUv.x - 2.0 * h;',
			'float lef1 = vUv.x - 1.0 * h;',
			'float rig1 = vUv.x + 1.0 * h;',
			'float rig2 = vUv.x + 2.0 * h;',
			'float rig3 = vUv.x + 3.0 * h;',
			'float rig4 = vUv.x + 4.0 * h;',

			'lef4 = lef4 >= 0.0 ? lef4 : (1.0 + lef4);',
			'lef4 = lef4 < 1.0  ? lef4 : (lef4 - 1.0 );',
			'lef3 = lef3 >= 0.0 ? lef3 : (1.0 + lef3);',
			'lef3 = lef3 < 1.0  ? lef3 : (lef3 - 1.0 );',
			'lef2 = lef2 >= 0.0 ? lef2 : (1.0 + lef2);',
			'lef2 = lef2 < 1.0  ? lef2 : (lef2 - 1.0 );',
			'lef1 = lef1 >= 0.0 ? lef1 : (1.0 + lef1);',
			'lef1 = lef1 < 1.0  ? lef1 : (lef1 - 1.0 );',
			'rig1 = rig1 >= 0.0 ? rig1 : (1.0 + rig1);',
			'rig1 = rig1 < 1.0  ? rig1 : (rig1 - 1.0 );',
			'rig2 = rig2 >= 0.0 ? rig2 : (1.0 + rig2);',
			'rig2 = rig2 < 1.0  ? rig2 : (rig2 - 1.0 );',
			'rig3 = rig3 >= 0.0 ? rig3 : (1.0 + rig3);',
			'rig3 = rig3 < 1.0  ? rig3 : (rig3 - 1.0 );',
			'rig4 = rig4 >= 0.0 ? rig4 : (1.0 + rig4);',
			'rig4 = rig4 < 1.0  ? rig4 : (rig4 - 1.0 );',

			'sum += texture2D( tDiffuse, vec2( lef4, vUv.y ) ) * 0.051;',
			'sum += texture2D( tDiffuse, vec2( lef3, vUv.y ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( lef2, vUv.y ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( lef1, vUv.y ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, vUv.y ) ) * 0.1633;',
			'sum += texture2D( tDiffuse, vec2( rig1, vUv.y ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( rig2, vUv.y ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( rig3, vUv.y ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( rig4, vUv.y ) ) * 0.051;',
			'if (h > 0.0){',
			'	vec4 srcValue = texture2D( tDiffuse, vec2( vUv.x, vUv.y ) );',
			'	sum = srcValue + srcValue - sum;',
			'}',
			'gl_FragColor = sum;',
			//'gl_FragColor = vec4(1,0,0,1);',

		'}'

	].join('\n')

};


NORMALGEN.VerticalBlurShader = {

	uniforms: {

		'tDiffuse': { type: 't', value: null },
		'v':        { type: 'f', value: 3.0 / 512.0 }

	},

	vertexShader: [

		'varying vec2 vUv;',

		'void main() {',

			'vUv = uv;',
			'gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',

		'}'

	].join('\n'),

	fragmentShader: [

		'uniform sampler2D tDiffuse;',
		'uniform float v;',

		'varying vec2 vUv;',

		'void main() {',

			'vec4 sum = vec4( 0.0 );',
			'float top4 = vUv.y - 4.0 * v;',
			'float top3 = vUv.y - 3.0 * v;',
			'float top2 = vUv.y - 2.0 * v;',
			'float top1 = vUv.y - 1.0 * v;',
			'float bot1 = vUv.y + 1.0 * v;',
			'float bot2 = vUv.y + 2.0 * v;',
			'float bot3 = vUv.y + 3.0 * v;',
			'float bot4 = vUv.y + 4.0 * v;',

			'top4 = top4 >= 0.0 ? top4 : (1.0 + top4);',
			'top4 = top4 < 1.0  ? top4 : (top4 - 1.0 );',
			'top3 = top3 >= 0.0 ? top3 : (1.0 + top3);',
			'top3 = top3 < 1.0  ? top3 : (top3 - 1.0 );',
			'top2 = top2 >= 0.0 ? top2 : (1.0 + top2);',
			'top2 = top2 < 1.0  ? top2 : (top2 - 1.0 );',
			'top1 = top1 >= 0.0 ? top1 : (1.0 + top1);',
			'top1 = top1 < 1.0  ? top1 : (top1 - 1.0 );',
			'bot1 = bot1 >= 0.0 ? bot1 : (1.0 + bot1);',
			'bot1 = bot1 < 1.0  ? bot1 : (bot1 - 1.0 );',
			'bot2 = bot2 >= 0.0 ? bot2 : (1.0 + bot2);',
			'bot2 = bot2 < 1.0  ? bot2 : (bot2 - 1.0 );',
			'bot3 = bot3 >= 0.0 ? bot3 : (1.0 + bot3);',
			'bot3 = bot3 < 1.0  ? bot3 : (bot3 - 1.0 );',
			'bot4 = bot4 >= 0.0 ? bot4 : (1.0 + bot4);',
			'bot4 = bot4 < 1.0  ? bot4 : (bot4 - 1.0 );',

			'sum += texture2D( tDiffuse, vec2( vUv.x, top4 ) ) * 0.051;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, top3 ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, top2 ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, top1 ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, vUv.y ) ) * 0.1633;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot1 ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot2 ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot3 ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot4 ) ) * 0.051;',
			'if (v > 0.0){',
			'	vec4 srcValue = texture2D( tDiffuse, vec2( vUv.x, vUv.y ) );',
			'	sum = srcValue + srcValue - sum;',
			'}',
			'gl_FragColor = sum;',

		'}'

	].join('\n')
};



// generateNormalMap puzzle
function generateNormalMap(srcURL, strength, level, blur, filter, invertR, invertG, invertHeight) {

    return new Promise(function(resolve, reject) {

        var heightImage = new Image();
        heightImage.src = srcURL;
        heightImage.onload = function() {

            var output = NORMALGEN.convert(heightImage,
                {
                    width: heightImage.width,
                    height: heightImage.height,
                    strength: strength,
                    level: level,
                    blur: blur,
                    filter: filter,
                    invertR: invertR,
                    invertG: invertG,
                    invertHeight: invertHeight
                }
            );
            resolve(output);
        };

        heightImage.onerror = function() {

            var pink = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAAC' +
                'QkWg2AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wgNDjoFwUNXbAAAABpJREF' +
                'UKM9jfF52jYEUwMRAIhjVMKph6GgAAOxFAlM1pWHTAAAAAElFTkSuQmCC';

            resolve(pink); // return a pink image instead of failing
        };

    });

}



// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;
        elem.addEventListener(eventType, callback, false);
    }
}



/**
 * Retreive standard accessible textures for MeshNodeMaterial or MeshStandardMaterial.
 * If "collectSameNameMats" is true then all materials in the scene with the given name will
 * be used for collecting textures, otherwise will be used only the first found material (default behavior).
 */
function matGetEditableTextures(matName, collectSameNameMats) {

    var mats = [];
    if (collectSameNameMats) {
        mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
    } else {
        var firstMat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
        if (firstMat !== null) {
            mats = [firstMat];
        }
    }

    var textures = mats.reduce(function(texArray, mat) {
        var matTextures = [];
        switch (mat.type) {
            case 'MeshNodeMaterial':
                matTextures = Object.values(mat.nodeTextures);
                break;

            case 'MeshStandardMaterial':
                matTextures = [
                    mat.map, mat.lightMap, mat.aoMap, mat.emissiveMap,
                    mat.bumpMap, mat.normalMap, mat.displacementMap,
                    mat.roughnessMap, mat.metalnessMap, mat.alphaMap, mat.envMap
                ]
                break;

            default:
                console.error('matGetEditableTextures: Unknown material type ' + mat.type);
                break;
        }

        Array.prototype.push.apply(texArray, matTextures);
        return texArray;
    }, []);

    return textures.filter(function(elem) {
        // check Texture type exactly
        return elem && (elem.constructor == v3d.Texture
                || elem.constructor == v3d.DataTexture
                || elem.constructor == v3d.VideoTexture);
    });
}



/**
 * Replace accessible textures for MeshNodeMaterial or MeshStandardMaterial
 */
function matReplaceEditableTexture(mat, oldTex, newTex) {

    switch (mat.type) {
        case 'MeshNodeMaterial':
            for (var name in mat.nodeTextures) {
                if (mat.nodeTextures[name] == oldTex) {
                    mat.nodeTextures[name] = newTex;
                }
            }

            break;

        case 'MeshStandardMaterial':

            var texNames = ['map', 'lightMap', 'aoMap', 'emissiveMap',
                            'bumpMap', 'normalMap', 'displacementMap', 'roughnessMap',
                            'metalnessMap', 'alphaMap', 'envMap'];

            texNames.forEach(function(name) {
                if (mat[name] == oldTex) {
                    mat[name] = newTex;
                }
            });

            break;

        default:
            console.error('matReplaceEditableTexture: Unsupported material type ' + mat.type);
            break;
    }

}



// replaceTexture puzzle
function replaceTexture(matName, texName, texUrlOrElem, doCb) {

    var textures = matGetEditableTextures(matName, true).filter(function(elem) {
        return elem.name == texName;
    });

    if (!textures.length)
        return;

    if (texUrlOrElem instanceof Promise) {

        texUrlOrElem.then(function(response) {
           processImageUrl(response);
        }, function(error) {});

    } else if (typeof texUrlOrElem == 'string') {

        processImageUrl(texUrlOrElem);

    /**
     * NOTE: not checking for the MediaHTML5 constructor, because otherwise this
     * puzzle would always provide the code that's not needed most of the time
     */
    } else if (texUrlOrElem instanceof Object && texUrlOrElem.source
            instanceof HTMLVideoElement) {

        processVideo(texUrlOrElem.source);

    } else if (texUrlOrElem instanceof HTMLCanvasElement) {

        processCanvas(texUrlOrElem);

    } else {

        return;

    }

    function processImageUrl(url) {

        var isHDR = (url.search(/\.hdr$/) > 0);

        if (!isHDR) {
            var loader = new v3d.ImageLoader();
            loader.setCrossOrigin('Anonymous');
        } else {
            var loader = new v3d.FileLoader();
            loader.setResponseType('arraybuffer');
        }

        loader.load(url, function(image) {
            // JPEGs can't have an alpha channel, so memory can be saved by storing them as RGB.
            var isJPEG = url.search(/\.(jpg|jpeg)$/) > 0 || url.search(/^data\:image\/jpeg/) === 0;

            textures.forEach(function(elem) {

                if (!isHDR) {
                    elem.image = image;
                } else {
                    // parse loaded HDR buffer
                    var rgbeLoader = new v3d.RGBELoader();
                    var texData = rgbeLoader.parse(image);

                    // NOTE: reset params since the texture may be converted to float
                    elem.type = v3d.UnsignedByteType;
                    elem.encoding = v3d.RGBEEncoding;

                    elem.image = {
                        data: texData.data,
                        width: texData.width,
                        height: texData.height
                    }

                    elem.magFilter = v3d.LinearFilter;
                    elem.minFilter = v3d.LinearFilter;
                    elem.generateMipmaps = false;
                    elem.isDataTexture = true;

                }

                elem.format = isJPEG ? v3d.RGBFormat : v3d.RGBAFormat;
                elem.needsUpdate = true;

                // update world material if it is using this texture
                var wMat = appInstance.worldMaterial;
                if (wMat)
                    for (var texName in wMat.nodeTextures)
                        if (wMat.nodeTextures[texName] == elem)
                            appInstance.updateEnvironment(wMat);

            });

            // exec once
            doCb();

        });
    }

    function processVideo(elem) {
        var videoTex = new v3d.VideoTexture(elem);
        videoTex.flipY = false;
        videoTex.name = texName;

        var videoAssigned = false;

        var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
        mats.forEach(function(mat) {

            textures.forEach(function(tex) {
                matReplaceEditableTexture(mat, tex, videoTex);
            });

            mat.needsUpdate = true;
            videoAssigned = true;
        });

        if (videoAssigned)
            doCb();

    }

    function processCanvas(elem) {
        var canvasTex = new v3d.CanvasTexture(elem);
        canvasTex.flipY = false;
        canvasTex.name = texName;

        var canvasAssigned = false;

        var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
        mats.forEach(function(mat) {

            textures.forEach(function(tex) {
                matReplaceEditableTexture(mat, tex, canvasTex);
            });

            mat.needsUpdate = true;
            canvasAssigned = true;
        });

        if (canvasAssigned) {

            if (v3d.PL) {
                v3d.PL.canvasTextures = v3d.PL.canvasTextures || {};
                v3d.PL.canvasTextures[canvasTex.image.id] = canvasTex;
            }

            doCb();
        }

    }
}


// Describe this function...
function update_engraving() {
  replaceTexture('metall', 'engrave_ao', engraving_ao, function() {});
  replaceTexture('metall', 'engrave_normal', engraving_normal, function() {});
}


function matGetValues(matName) {

    var mat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
    if (!mat)
        return [];

    if (mat.isMeshNodeMaterial)
        return Object.keys(mat.nodeValueMap);
    else if (mat.isMeshStandardMaterial)
        return ['metalness', 'roughness', 'bumpScale', 'emissiveIntensity', 'envMapIntensity'];
    else
        return [];
}



// setMaterialValue puzzle
function setMaterialValue(matName, valName, value) {

    var values = matGetValues(matName);
    if (values.indexOf(valName) < 0)
        return;

    var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);

    for (var i = 0; i < mats.length; i++) {
        var mat = mats[i];

        if (mat.isMeshNodeMaterial) {
            var valIdx = mat.nodeValueMap[valName];
            mat.nodeValue[valIdx] = Number(value);
        } else
            mat[valName] = Number(value);

        if (mat === appInstance.worldMaterial)
            appInstance.updateEnvironment(mat);
    }
}



function matGetColors(matName) {
    var mat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
    if (!mat)
        return [];

    if (mat.isMeshNodeMaterial)
        return Object.keys(mat.nodeRGBMap);
    else if (mat.isMeshStandardMaterial)
        return ['color', 'emissive'];
    else
        return [];
}



// setMaterialColor puzzle
function setMaterialColor(matName, colName, r, g, b, cssCode) {

    var colors = matGetColors(matName);

    if (colors.indexOf(colName) < 0)
        return;

    if (cssCode) {
        var color = new v3d.Color(cssCode);
        color.convertSRGBToLinear();
        r = color.r;
        g = color.g;
        b = color.b;
    }

    var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);

    for (var i = 0; i < mats.length; i++) {
        var mat = mats[i];

        if (mat.isMeshNodeMaterial) {
            var rgbIdx = mat.nodeRGBMap[colName];
            mat.nodeRGB[rgbIdx].x = r;
            mat.nodeRGB[rgbIdx].y = g;
            mat.nodeRGB[rgbIdx].z = b;
        } else {
            mat[colName].r = r;
            mat[colName].g = g;
            mat[colName].b = b;
        }
        mat.needsUpdate = true;

        if (mat === appInstance.worldMaterial)
            appInstance.updateEnvironment(mat);
    }
}


// Describe this function...
function metall_material_update() {
  setMaterialValue('metall', 'metall_roughness', metall_colors[0]);
  setMaterialColor('metall', 'metall_color_1', metall_colors[1], metall_colors[2], metall_colors[3], '');
  setMaterialColor('metall', 'metall_color_2', metall_colors[4], metall_colors[5], metall_colors[6], '');
}

// Describe this function...
function gem_color_update() {
  setMaterialColor('gem_outer', 'gem_color', gem_colors[0], gem_colors[1], gem_colors[2], '');
}

function textReplace(haystack, needle, replacement) {
  needle = needle.replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1")
                 .replace(/\x08/g,"\\x08");
  return haystack.replace(new RegExp(needle, 'g'), replacement);
}

// Describe this function...
function buttons_select_remove() {
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_ring_type_' + String(ring_type), true), 'ring-button-selected', ''), 'button_ring_type_' + String(ring_type), true);
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_ring_gem_' + String(gem_type), true), 'ring-button-selected', ''), 'button_ring_gem_' + String(gem_type), true);
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_curve_' + String(curve_type), true), 'ring-button-selected', ''), 'button_curve_' + String(curve_type), true);
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_line_' + String(line_type), true), 'ring-button-selected', ''), 'button_line_' + String(line_type), true);
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_material_' + String(material), true), 'ring-button-selected', ''), 'button_material_' + String(material), true);
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_gem_color_' + String(gem_color), true), 'ring-button-selected', ''), 'button_gem_color_' + String(gem_color), true);
  setHTMLElemAttribute('className', textReplace(getHTMLElemAttribute('className', 'button_pearl_color_' + String(pearl_color), true), 'ring-button-selected', ''), 'button_pearl_color_' + String(pearl_color), true);
}

// Describe this function...
function buttons_select_apply() {
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_ring_type_' + String(ring_type), true)) + ' ring-button-selected', 'button_ring_type_' + String(ring_type), true);
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_ring_gem_' + String(gem_type), true)) + ' ring-button-selected', 'button_ring_gem_' + String(gem_type), true);
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_curve_' + String(curve_type), true)) + ' ring-button-selected', 'button_curve_' + String(curve_type), true);
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_line_' + String(line_type), true)) + ' ring-button-selected', 'button_line_' + String(line_type), true);
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_material_' + String(material), true)) + ' ring-button-selected', 'button_material_' + String(material), true);
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_gem_color_' + String(gem_color), true)) + ' ring-button-selected', 'button_gem_color_' + String(gem_color), true);
  setHTMLElemAttribute('className', String(getHTMLElemAttribute('className', 'button_pearl_color_' + String(pearl_color), true)) + ' ring-button-selected', 'button_pearl_color_' + String(pearl_color), true);
}

// Describe this function...
function html_buttons_acess_update() {
  if (gem_type == 0) {
    setHTMLElemStyle('display', 'block', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'none', 'button_line_2', true);
    setHTMLElemStyle('display', 'block', 'button_line_1', true);
    setHTMLElemStyle('display', 'none', 'buttons_pearl_colors', true);
    setHTMLElemStyle('display', 'block', 'buttons_gem_colors', true);
  } else if (gem_type == 1) {
    setHTMLElemStyle('display', 'none', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'none', 'button_line_1', true);
    setHTMLElemStyle('display', 'block', 'button_line_2', true);
    setHTMLElemStyle('display', 'none', 'buttons_pearl_colors', true);
    setHTMLElemStyle('display', 'block', 'buttons_gem_colors', true);
  } else if (gem_type == 9) {
    setHTMLElemStyle('display', 'none', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'block', 'button_line_0', true);
    setHTMLElemStyle('display', 'block', 'button_line_1', true);
    setHTMLElemStyle('display', 'block', 'button_line_2', true);
    setHTMLElemStyle('display', 'none', 'buttons_pearl_colors', true);
    setHTMLElemStyle('display', 'block', 'buttons_gem_colors', true);
  } else if (gem_type == 10) {
    setHTMLElemStyle('display', 'none', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'block', 'button_line_0', true);
    setHTMLElemStyle('display', 'none', 'button_line_1', true);
    setHTMLElemStyle('display', 'none', 'button_line_2', true);
    setHTMLElemStyle('display', 'none', 'buttons_gem_colors', true);
    setHTMLElemStyle('display', 'block', 'buttons_pearl_colors', true);
  } else {
    setHTMLElemStyle('display', 'none', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'none', 'button_line_2', true);
    setHTMLElemStyle('display', 'block', 'button_line_1', true);
    setHTMLElemStyle('display', 'none', 'buttons_pearl_colors', true);
    setHTMLElemStyle('display', 'block', 'buttons_gem_colors', true);
  }
  if (line_type == 0 && gem_type == 0) {
    setHTMLElemStyle('display', 'block', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'block', ['button_ring_gem_0', 'button_ring_gem_1', 'button_ring_gem_2', 'button_ring_gem_3', 'button_ring_gem_4', 'button_ring_gem_5', 'button_ring_gem_6', 'button_ring_gem_7', 'button_ring_gem_8', 'button_ring_gem_9'], true);
  } else if (line_type == 0 && gem_type != 0) {
    setHTMLElemStyle('display', 'block', ['button_ring_gem_0', 'button_ring_gem_1', 'button_ring_gem_2', 'button_ring_gem_3', 'button_ring_gem_4', 'button_ring_gem_5', 'button_ring_gem_6', 'button_ring_gem_7', 'button_ring_gem_8', 'button_ring_gem_9', 'button_ring_gem_10'], true);
  } else if (line_type == 1) {
    setHTMLElemStyle('display', 'none', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'block', ['button_ring_gem_0', 'button_ring_gem_2', 'button_ring_gem_3', 'button_ring_gem_4', 'button_ring_gem_5', 'button_ring_gem_6', 'button_ring_gem_7', 'button_ring_gem_8', 'button_ring_gem_9'], true);
    setHTMLElemStyle('display', 'none', 'button_ring_gem_10', true);
    setHTMLElemStyle('display', 'none', 'button_ring_gem_1', true);
  } else if (line_type == 2) {
    setHTMLElemStyle('display', 'none', ['button_curve_1', 'button_curve_2', 'button_curve_3', 'button_curve_4'], true);
    setHTMLElemStyle('display', 'none', ['button_ring_gem_0', 'button_ring_gem_2', 'button_ring_gem_3', 'button_ring_gem_4', 'button_ring_gem_5', 'button_ring_gem_6', 'button_ring_gem_7', 'button_ring_gem_8', 'button_ring_gem_10'], true);
    setHTMLElemStyle('display', 'block', 'button_ring_gem_1', true);
    setHTMLElemStyle('display', 'block', 'button_ring_gem_9', true);
  }
  if (curve_type == 0 && line_type == 0) {
    setHTMLElemStyle('display', 'block', ['button_ring_gem_1', 'button_ring_gem_2', 'button_ring_gem_3', 'button_ring_gem_4', 'button_ring_gem_5', 'button_ring_gem_6', 'button_ring_gem_7', 'button_ring_gem_8', 'button_ring_gem_9', 'button_ring_gem_10'], true);
  } else if (curve_type != 0) {
    setHTMLElemStyle('display', 'none', ['button_ring_gem_1', 'button_ring_gem_2', 'button_ring_gem_3', 'button_ring_gem_4', 'button_ring_gem_5', 'button_ring_gem_6', 'button_ring_gem_7', 'button_ring_gem_8', 'button_ring_gem_9', 'button_ring_gem_10'], true);
    setHTMLElemStyle('display', 'none', ['button_line_1', 'button_line_2'], true);
  }
}


// unloadScene puzzle
function unloadScene(url) {
    if (appInstance.scene) {
        var scene = url === '' ? appInstance.scene : appInstance.scene.getObjectByName(url);
        if (scene) appInstance.unload(scene);

        if (!appInstance.scene) appInstance.renderer.clear();

        // clean object cache
        _pGlob.objCache = {};
    }
}


// Describe this function...
function load_gem_set(gem_number) {
  setHTMLElemStyle('display', 'block', 'local_preloader_screen', true);
  for (var i_index in gem_loaded) {
    i = gem_loaded[i_index];
    if (i == true) {
      unloadScene(['gem_',i_count,'.gltf'].join(''));
      gem_loaded[i_count] = false;
    }
    i_count = (typeof i_count == 'number' ? i_count : 0) + 1;
  }
  appendScene(['gem_',gem_number,'.gltf.xz'].join(''), ['gem_',gem_number,'.gltf.xz'].join(''), false, false, function() {
    buttons_select_remove();
    gem_type = gem_number;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[gem_number] = true;
    setHTMLElemStyle('display', 'none', 'local_preloader_screen', true);
    metall_material_update();
    gem_color_update();
    i_count = 0;
    update_engraving();
  }, function() {
    setHTMLElemAttribute('innerHTML', String(Math.round(_pGlob.percentage)) + '%', 'local_preloader_percentage', true);
  });
}


current_ring = 'type_1_gem_0_curve_0_line_0';
ring_type = 1;
gem_type = 0;
curve_type = 0;
line_type = 0;
material = 1;
gem_color = 1;
pearl_color = 1;
gem_loaded = [false, false, false, false];
appendScene('gem_0.gltf.xz', 'gem_0.gltf.xz', false, false, function() {
  buttons_select_remove();
  gem_type = 0;
  html_buttons_acess_update();
  ring_update();
  gem_loaded[0] = true;
  registerSetTimeout(0.5, function() {
    setHTMLElemStyle('display', 'none', 'preloader_screen', true);
  });
  metall_material_update();
}, function() {
  setHTMLElemAttribute('innerHTML', String(Math.round(25 + Math.round(_pGlob.percentage) * 0.75)) + '%', 'preloader_percentage', true);
  setHTMLElemStyle('height', String(Math.round(25 + Math.round(_pGlob.percentage) * 0.75)) + '%', 'preloader_color', true);
});
i_count = 0;

if (featureAvailable('MOBILE') == true) {
  tweenCamera('mobile_camera_place', 'camera_look_at', 0, function() {}, 0);
}

setHTMLElemStyle('display', 'none', 'fullscreen_button', false);
if (featureAvailable('MOBILE') == false) {
  bloom(1, 0.3, 0.5);
  setScreenScale(1.5);
} else {
  setScreenScale(1.3);
}

eventHTMLElem('click', 'button_clear', true, function(event) {
  engraving_ao = textureFromText('', 1024, 256, getHTMLElemAttribute('value', 'engrave_font', true), 100, 'CENTER', 5);
  engraving_normal = generateNormalMap(engraving_ao, 0.002, 0.002, -1, 'Sobel', false, false, false);
  update_engraving();
});
eventHTMLElem('click', 'button_engrave', true, function(event) {
  if (getHTMLElemAttribute('value', 'engrave_text', true).length < 12) {
    engraving_ao = textureFromText(getHTMLElemAttribute('value', 'engrave_text', true), 1024, 256, getHTMLElemAttribute('value', 'engrave_font', true), 100, 'CENTER', 5);
    engraving_normal = generateNormalMap(engraving_ao, 0.002, 0.002, -1, 'Sobel', false, false, false);
    update_engraving();
  } else {
    engraving_ao = textureFromText(getHTMLElemAttribute('value', 'engrave_text', true), 1024, 256, getHTMLElemAttribute('value', 'engrave_font', true), 100, 'FIT', 5);
    engraving_normal = generateNormalMap(engraving_ao, 0.002, 0.002, -1, 'Sobel', false, false, false);
    update_engraving();
  }
});

metall_colors = [0, 0.808, 0.808, 0.808, 0.624, 0.624, 0.624];
gem_colors = [1, 1, 1];

eventHTMLElem('click', 'button_ring_type_1', true, function(event) {
  buttons_select_remove();
  ring_type = 1;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_ring_type_2', true, function(event) {
  buttons_select_remove();
  ring_type = 2;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_ring_type_3', true, function(event) {
  buttons_select_remove();
  ring_type = 3;
  ring_update();
});
eventHTMLElem('click', 'button_ring_type_4', true, function(event) {
  buttons_select_remove();
  ring_type = 4;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_ring_type_5', true, function(event) {
  buttons_select_remove();
  ring_type = 5;
  html_buttons_acess_update();
  ring_update();
});

eventHTMLElem('click', 'button_ring_gem_0', true, function(event) {
  if (gem_loaded[0] == true) {
    buttons_select_remove();
    gem_type = 0;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[0] = true;
    metall_material_update();
  } else {
    load_gem_set(0);
  }
});
eventHTMLElem('click', 'button_ring_gem_1', true, function(event) {
  if (gem_loaded[1] == true) {
    buttons_select_remove();
    gem_type = 1;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[1] = true;
    metall_material_update();
  } else {
    load_gem_set(1);
  }
});
eventHTMLElem('click', 'button_ring_gem_2', true, function(event) {
  if (gem_loaded[2] == true) {
    buttons_select_remove();
    gem_type = 2;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[2] = true;
    metall_material_update();
  } else {
    load_gem_set(2);
  }
});
eventHTMLElem('click', 'button_ring_gem_3', true, function(event) {
  if (gem_loaded[3] == true) {
    buttons_select_remove();
    gem_type = 3;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[3] = true;
    metall_material_update();
  } else {
    load_gem_set(3);
  }
});
eventHTMLElem('click', 'button_ring_gem_4', true, function(event) {
  if (gem_loaded[4] == true) {
    buttons_select_remove();
    gem_type = 4;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[4] = true;
    metall_material_update();
  } else {
    load_gem_set(4);
  }
});
eventHTMLElem('click', 'button_ring_gem_5', true, function(event) {
  if (gem_loaded[5] == true) {
    buttons_select_remove();
    gem_type = 5;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[5] = true;
    metall_material_update();
  } else {
    load_gem_set(5);
  }
});
eventHTMLElem('click', 'button_ring_gem_6', true, function(event) {
  if (gem_loaded[6] == true) {
    buttons_select_remove();
    gem_type = 6;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[6] = true;
    metall_material_update();
  } else {
    load_gem_set(6);
  }
});
eventHTMLElem('click', 'button_ring_gem_7', true, function(event) {
  if (gem_loaded[7] == true) {
    buttons_select_remove();
    gem_type = 7;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[7] = true;
    metall_material_update();
  } else {
    load_gem_set(7);
  }
});
eventHTMLElem('click', 'button_ring_gem_8', true, function(event) {
  if (gem_loaded[8] == true) {
    buttons_select_remove();
    gem_type = 8;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[8] = true;
    metall_material_update();
  } else {
    load_gem_set(8);
  }
});
eventHTMLElem('click', 'button_ring_gem_9', true, function(event) {
  if (gem_loaded[9] == true) {
    buttons_select_remove();
    gem_type = 9;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[9] = true;
    metall_material_update();
  } else {
    load_gem_set(9);
  }
});
eventHTMLElem('click', 'button_ring_gem_10', true, function(event) {
  if (gem_loaded[10] == true) {
    buttons_select_remove();
    gem_type = 10;
    html_buttons_acess_update();
    ring_update();
    gem_loaded[10] = true;
    metall_material_update();
  } else {
    load_gem_set(10);
  }
});

eventHTMLElem('click', 'button_line_0', true, function(event) {
  buttons_select_remove();
  line_type = 0;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_line_1', true, function(event) {
  buttons_select_remove();
  line_type = 1;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_line_2', true, function(event) {
  buttons_select_remove();
  line_type = 2;
  html_buttons_acess_update();
  ring_update();
});

eventHTMLElem('click', 'button_curve_0', true, function(event) {
  buttons_select_remove();
  curve_type = 0;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_curve_1', true, function(event) {
  buttons_select_remove();
  curve_type = 1;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_curve_2', true, function(event) {
  buttons_select_remove();
  curve_type = 2;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_curve_3', true, function(event) {
  buttons_select_remove();
  curve_type = 3;
  html_buttons_acess_update();
  ring_update();
});
eventHTMLElem('click', 'button_curve_4', true, function(event) {
  buttons_select_remove();
  curve_type = 4;
  html_buttons_acess_update();
  ring_update();
});

eventHTMLElem('click', 'button_material_1', true, function(event) {
  buttons_select_remove();
  material = 1;
  html_buttons_acess_update();
  metall_colors = [0, 0.808, 0.808, 0.808, 0.624, 0.624, 0.624];
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_material_2', true, function(event) {
  buttons_select_remove();
  material = 2;
  html_buttons_acess_update();
  metall_colors = [0, 0.977, 0.827, 0.299611, 0.603, 0.366, 0];
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_material_3', true, function(event) {
  buttons_select_remove();
  material = 3;
  html_buttons_acess_update();
  metall_colors = [0, 0.977, 0.638, 0.449, 0.604, 0.21, 0.069];
  metall_material_update();
  buttons_select_apply();
});

eventHTMLElem('click', 'button_gem_color_1', true, function(event) {
  buttons_select_remove();
  gem_color = 1;
  gem_colors = [0.8, 0.8, 0.8];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_gem_color_2', true, function(event) {
  buttons_select_remove();
  gem_color = 2;
  gem_colors = [0.38483, 0.82551, 1];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_gem_color_3', true, function(event) {
  buttons_select_remove();
  gem_color = 3;
  gem_colors = [1, 0.157652, 0.658391];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_gem_color_4', true, function(event) {
  buttons_select_remove();
  gem_color = 4;
  gem_colors = [1, 0.159356, 0.034049];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_gem_color_5', true, function(event) {
  buttons_select_remove();
  gem_color = 5;
  gem_colors = [0.018249, 0.050723, 1];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_gem_color_6', true, function(event) {
  buttons_select_remove();
  gem_color = 6;
  gem_colors = [0.013456, 0.358734, 0];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_gem_color_7', true, function(event) {
  buttons_select_remove();
  gem_color = 7;
  gem_colors = [0.380056, 0, 0.083378];
  gem_color_update();
  html_buttons_acess_update();
  metall_material_update();
  buttons_select_apply();
});

eventHTMLElem('click', 'button_pearl_color_1', true, function(event) {
  buttons_select_remove();
  pearl_color = 1;
  setMaterialColor('pearl', 'color', 0.799103, 0.723055, 0.564712, '');
  html_buttons_acess_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_pearl_color_2', true, function(event) {
  buttons_select_remove();
  pearl_color = 2;
  setMaterialColor('pearl', 'color', 0.679283, 0.770726, 0.8, '');
  html_buttons_acess_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_pearl_color_3', true, function(event) {
  buttons_select_remove();
  pearl_color = 3;
  setMaterialColor('pearl', 'color', 1, 0.787344, 0.762103, '');
  html_buttons_acess_update();
  buttons_select_apply();
});
eventHTMLElem('click', 'button_pearl_color_4', true, function(event) {
  buttons_select_remove();
  pearl_color = 4;
  setMaterialColor('pearl', 'color', 0.131874, 0.127406, 0.162208, '');
  html_buttons_acess_update();
  buttons_select_apply();
});



} // end of PL.init function

})(); // end of closure

/* ================================ end of code ============================= */
